language: bash
services: docker

env:
  - VERSION=17.03 VARIANT=bash

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}-${VARIANT:+/$VARIANT}"
  - image="mlaccetti:${VERSION}-${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
