dist: trusty
language: bash
services: docker

matrix:
  include:
  - bash: 4
    env:
    - VERSION=17.03.0-ce VARIANT=bash
  - bash: 4
    env:
    - VERSION=17.03.1-ce VARIANT=bash
  - bash: 4
    env:
    - VERSION=17.04.0-ce VARIANT=bash

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}-${VARIANT:+$VARIANT}"
  - image="mlaccetti:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
