dist: trusty
language: go
services: docker

matrix:
  include:
  - go: '1.x'
    env:
    - VERSION=17.03.0-ce VARIANT=bash
  - go: '1.x'
    env:
    - VERSION=17.03.1-ce VARIANT=bash
  - go: '1.x'
    env:
    - VERSION=17.04.0-ce VARIANT=bash
  - go: '1.x'
    env:
    - VERSION=17.05.0-ce VARIANT=bash
  - go: '1.x'
    env:
    - VERSION=17.06.0-ce VARIANT=bash
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}-${VARIANT:+$VARIANT}"
  - image="mlaccetti/docker-bash:${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "mlaccetti/docker-bash:${VERSION}";
    fi
